openapi: 3.0.1
info:
  title: RecordPagos API
  description: API para gestionar registros de pagos.
  version: "1.0.0"

components:
  schemas:
    RecordPagos:
      type: object
      required:
        - id_Record
        - id_Deuda
        - fechaPago
        - montoPagado
        - metodoPago
        - estadoPago
      properties:
        id_Record:
          type: number
          description: Identificador único del registro de pago.
        id_Deuda:
          type: number
          description: Identificador de la deuda asociada al registro de pago.
        fechaPago:
          type: string
          format: date
          description: Fecha en que se realizó el pago.
        montoPagado:
          type: number
          description: Monto pagado en la transacción.
        metodoPago:
          type: string
          description: Método utilizado para realizar el pago (ej. tarjeta, efectivo, transferencia).
        estadoPago:
          type: string
          enum:
            - pendiente
            - pagado
            - devuelto
          description: Estado del pago.
      example:
        id_Record: 1
        id_Deuda: 101
        fechaPago: "2024-10-15T00:00:00.000Z"
        montoPagado: 200.00
        metodoPago: "transferencia"
        estadoPago: "pagado"

paths:
  /api/recordpago:
    post:
      summary: Crear un nuevo registro de pago
      tags: [RecordPagos]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecordPagos'
      responses:
        '201':
          description: ¡Registro de pago creado exitosamente!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Registro de pago creado exitosamente"
                  data:
                    $ref: '#/components/schemas/RecordPagos'
        '400':
          description: Error al crear el registro de pago.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error al crear el registro de pago. Revisa los datos enviados."

    get:
      summary: Obtener todos los registros de pago
      tags: [RecordPagos]
      responses:
        '200':
          description: Lista de todos los registros de pago.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecordPagos'
        '500':
          description: Error al obtener los registros de pago.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error al obtener los registros de pago."

  /api/recordpago/{id_Record}:
    get:
      summary: Obtener un registro de pago por ID
      tags: [RecordPagos]
      parameters:
        - in: path
          name: id_Record
          schema:
            type: number
          required: true
          description: ID del registro de pago que se quiere obtener
      responses:
        '200':
          description: Registro de pago encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecordPagos'
        '404':
          description: Registro de pago no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Registro de pago no encontrado."
        '500':
          description: Error al obtener el registro de pago.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error al obtener el registro de pago."

  /api/recordpago/deuda/{id_Deuda}:
    get:
      summary: Obtener todos los registros de pago por ID de deuda
      tags: [RecordPagos]
      parameters:
        - in: path
          name: id_Deuda
          schema:
            type: number
          required: true
          description: ID de la deuda cuyos registros de pago se desean obtener
      responses:
        '200':
          description: Lista de todos los registros de pago para la deuda especificada.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecordPagos'
        '500':
          description: Error al obtener los registros de pago.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error al obtener los registros de pago."

  